// GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
// Source rows: scripts/photos.manifest.json. Originals live outside the repo.
export type SitePhoto = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
  altEs: string;
  altEn: string;
};

export const PHOTOS = {
  "contabilidad": {
    src: "/photos/contabilidad.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQAgCdASoQAAsAA4BaJZQAD42QhPesSHfgAP7n4qY8Odxz74AkORWXEPW5FNObDGTf9qQb2hZpbLFLV4r9nQ21nf1zCcbuUKl7Ck6BS3inDRdm2dkMeFSKMCNPgxUXdY5OCXaO5I6tBMsR3AmwAA==",
    altEs: "Dos colegas revisan juntos un reporte de gráficas impreso sobre la mesa",
    altEn: "Two colleagues going over a printed chart report together at the table",
  },
  "entrega-tablero": {
    src: "/photos/entrega-tablero.webp",
    width: 3200,
    height: 1800,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAkAA4BaJYwCdACC5FJgAP7dGn3A2X984VP315EpyY0TKYswE8ybA8UPA7X4WfXaNT1jat9cAI8Ek6wNKAAA",
    altEs: "Dos personas frente a una pared con notas de trabajo, ordenando las prioridades de un proyecto",
    altEn: "Two people at a wall of work notes, sorting out a project's priorities",
  },
  "experiencia-mostrador": {
    src: "/photos/experiencia-mostrador.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAsAA4BaJYwAAvyzZG9wzgAA/kJqS5WqjBcRdVkXnXLzNV/z5E9+P2nzlD+d85WCsSzpXN/efQdoGq1SBIuqGA4lWN5HxwddQ5AgohAAAA==",
    altEs: "En un mostrador de recepción, una persona atiende con una tableta a otra que llega, las dos de frente",
    altEn: "At a reception counter, someone with a tablet attends to a visitor, the two facing each other",
  },
  "mantenimiento": {
    src: "/photos/mantenimiento.webp",
    width: 2134,
    height: 3200,
    blurDataURL:
      "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBACdASoQABgAPu1iqk2ppaQiMAgBMB2JYwDA3B5UEm6F39bBqQ3CagAA/pFFIoZBT19Bdliq22lm6+2a/HPhnvwrbdM1N0rvuUfRoKjoCxy+ZUir9D1uyF4KV1c//TDJs/5l8aGBKoSFNPp1LFOsAEbnO7nSTYZRkAAA",
    altEs: "Personal técnico trabajando sobre maquinaria en planta",
    altEn: "Technical staff working on machinery on the plant floor",
  },
  "proceso-escrito": {
    src: "/photos/proceso-escrito.webp",
    width: 3200,
    height: 2134,
    blurDataURL:
      "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAsAA4BaJZQC7AYuvsGxBkk0AAD+9AxNUodRYd3VT9dfrnzdhXgoeQdeHWd/383iaui1vamOILHn1mhZap6wkfZb/l9KEAhOHxQ5lHd3OLrmON4ClXkdngA=",
    altEs: "Una persona anotando un diagrama en una libreta junto a una laptop",
    altEn: "Someone sketching a diagram in a notebook beside a laptop",
  },
  "capacitacion": {
    src: "/photos/capacitacion.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQAgCdASoQAAsAA4BaJQBOgMXI7Ws3LZWAAP6JTTa8xWoBfPAH23AqVmP1M+w1MHf7VL8TbwX0dvoTDoyPSOU2o/kxCidBcACr6vOnzIDIMBqF39ud4H07MCPa1znt7ld7Nqrb6P6J23R5IoYAAA==",
    altEs: "Una sesión en una sala de juntas con alguien presentando",
    altEn: "A session in a meeting room with someone presenting",
  },
  "asesoria": {
    src: "/photos/asesoria.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAAsAA4BaJagCdAYvhRgp8hveAAD+ypon4e27wdHnd7ojHQdvk4q5dzDZCUrGifxGMUJLxjCNlw6TJDEGbSjlPEvqME1hwSxI/hzT6W6Mvj0ZmJ0uRSI3Lf1glIAA",
    altEs: "Cuatro personas conversando frente a una laptop",
    altEn: "Four people talking around a laptop",
  },
  "quienes": {
    src: "/photos/quienes.webp",
    width: 3200,
    height: 1800,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAkAA4BaJaACdAYtVOYlC1rp4AD+T0zmxwCZDCi7F7xz073EcDPWiuMCpyUZQRz8oELmMAfPRjGVbY7YYUQtGQSaowUPCH4bCcQHEAAAAA==",
    altEs: "Dos colegas conversan sobre un documento en una oficina, con un pizarrón al fondo",
    altEn: "Two colleagues talk over a document in an office, with a chalkboard behind them",
  },
  "hablemos": {
    src: "/photos/hablemos.webp",
    width: 2400,
    height: 1350,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJQBOgBuRGw9SAAD+QJNSwTqX/hk+u2Mx5NMf8VKnEkAKXAtLdeZ/0g1wHvhtkWaS/T9vd21IxZs1LnpF0YnnlXqjRY1paA0AAA==",
    altEs: "Dos mujeres conversan en un escritorio de oficina, con una laptop entre ellas",
    altEn: "Two women talk at an office desk, with a laptop between them",
  },
  "recibimiento": {
    src: "/photos/recibimiento.webp",
    width: 3200,
    height: 2317,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwAA4BaJYwCdAC9iDcFUAAA/I6jYOvS5pC2QzT41lNtdKdVZcpK50MeZFj/pPeHeeathJZPSOybQ3oEM0jOIawVO8NyERmN5aFqDDB+RmgAAAA=",
    altEs: "Una mujer sonríe de pie en una oficina; detrás, su equipo trabaja en sus computadoras",
    altEn: "A woman smiles standing in an office; behind her, her team works at their computers",
  },
  "ia-operacion": {
    src: "/photos/ia-operacion.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwAgCdASoQAAsAA4BaJZQAD5FO315jvblIAAD+9YQskNg8abkrdn8WVyqTOSZQ1VljaGsoBJwjbVm4AXL7cCr+SzUgAtaPw8DqjnBae871llrxzX+FfKmVC2TJphW6zqRBGyYjkDTAAA==",
    altEs: "Una persona sentada frente a un muro de pantallas en una sala de operación, vigilando el trabajo que corre",
    altEn: "Someone seated before a wall of screens in an operations room, watching the work as it runs",
  },
  "nube-racks": {
    src: "/photos/nube-racks.webp",
    width: 3200,
    height: 1858,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAsAA4BaJZgCdAELjlp5P93AAP7xbwRWpf+tgwFbkbObPsND9akJY5pzQVTkUC/3uSxc+k13T9pakS3OPgBH0bFFTMphjciz5jhyD9buDbeSLso+8AAA",
    altEs: "Las manos de una persona sobre una laptop, de pie frente a los racks iluminados de un centro de datos",
    altEn: "A person's hands on a laptop, standing in front of the lit racks of a data centre",
  },
  "producto-pared": {
    src: "/photos/producto-pared.webp",
    width: 3200,
    height: 2136,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAsAA4BaJZwAD43vtxSBgAD+8f4TEcpbnoKEeuSWhQSC/CUBNvLMD7MEr1fauduR3y1Rtm47ZbtFkNShTtzbmT9MOAAA",
    altEs: "Una diseñadora explica los bocetos de las pantallas de una aplicación pegados en la pared",
    altEn: "A designer walks through sketches of an app's screens pinned to the wall",
  },
  "automotriz-motor": {
    src: "/photos/automotriz-motor.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAsAA4BaJZQCdAEVwrc8PagAAP7vaLabuf5BmEyJbIyGe4uIcBvmZqByDH1IwqrM+LuYhqQrzhx2ZtZNZBeGa6aFtgAA",
    altEs: "Una ingeniera con casco trabaja sobre una pieza de motor en un taller industrial",
    altEn: "An engineer in a hard hat works on an engine part in an industrial workshop",
  },
  "logistica-escaner": {
    src: "/photos/logistica-escaner.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAQCdASoQAAsAA4BaJYgCdADo7ASVTQAA/b8d1iVnjKxOMwZLojpsNHqqfT1FP9AqbxQLthTZB01ICLjLl/+iUu7ILBmcQGVp3/iCFDqsMkI5+lZtpnIv7nGAMZL7qXf4wm+NnNA+rlkAZw+zgAAA",
    altEs: "Un trabajador de almacén escanea un tambo con un lector y una tableta",
    altEn: "A warehouse worker scans a drum with a reader and a tablet",
  },
  "construccion-planos": {
    src: "/photos/construccion-planos.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAAsAA4BaJYgCdH8AGJpzNX140AD+34lueO45dq+Ah+9yTJcUCii1mn8z3Iq2hvzWJypARrB9indR69h1Fgigpg4ZvoTEbC1FBk3eTHlnLRBbfUmDBdaCSxsr8QAA",
    altEs: "Dos ingenieros revisan planos en una obra",
    altEn: "Two engineers go over drawings on a building site",
  },
  "comercio-contenedores": {
    src: "/photos/comercio-contenedores.webp",
    width: 3008,
    height: 2000,
    blurDataURL:
      "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQAAsAA4BaJbACdAYwTlVm4FPqYAD+I2sRotY2t4bl/sf1y+P0uAL2shz11wE80el8TIdcg5nP0+wshP4eg7rUMSK207jloNalpUZgO7YshU0GR1mPYszRKmZlYbIhTF9Nh6ffyAAAAA==",
    altEs: "Un trabajador portuario asegura contenedores en un buque",
    altEn: "A port worker secures containers on a ship",
  },
  "retail-tableta": {
    src: "/photos/retail-tableta.webp",
    width: 3200,
    height: 1800,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA4BaJQBOgCP0a174j8AAzizJWsOsrAnvPqv9005l9DA0oBPM9Nea+rtq/NbKRVKX3U1FA9vJQRoCLCx4oRTaIDI+m6Xn0nIJAAA=",
    altEs: "Una empleada revisa una tableta entre los percheros de una tienda de ropa",
    altEn: "A store employee checks a tablet between the racks of a clothing shop",
  },
  "farmaceutica-planta": {
    src: "/photos/farmaceutica-planta.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAsAA4BaJQBOgBh5JEj0AAD+7AX7tw8Aji6BMLo5/Ov46VB4CvRsegHnQChyYPh4Utmw+QqP3x4Po7Jwg2e+QD654wAA",
    altEs: "Personal con traje estéril dentro de una planta farmacéutica",
    altEn: "Staff in sterile suits inside a pharmaceutical plant",
  },
  "agricultura-cosecha": {
    src: "/photos/agricultura-cosecha.webp",
    width: 3200,
    height: 1799,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA4BaJYgCdAEU7znQoAD+W/zuFgCykCWjYwb9yszH/sxpY0DfeVgFNWg2XRp5/sZGSN3XB+B2sCzmvPNSuEH1gAAA",
    altEs: "Cuadrillas cosechan en un campo abierto, con los camiones de carga al fondo",
    altEn: "Crews harvest an open field, with the trucks in the background",
  },
  "manufactura-maquina": {
    src: "/photos/manufactura-maquina.webp",
    width: 3200,
    height: 2133,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAsAA4BaJZQAAxYYBNXdF3CAAP7lo8j47gVZelBrPpxDxLFVBmizl+WF6VF0rg8luOosEg648Gd7462XT48LgPyLvAgA",
    altEs: "Un operario revisa una pieza grande montada en un torno, dentro de una planta",
    altEn: "A worker checks a large part mounted on a lathe inside a plant",
  },
} as const satisfies Record<string, SitePhoto>;

export type PhotoSlug = keyof typeof PHOTOS;
