// optimize-photos.mjs — the photo pipeline of landing v2 §8, built in tanda C.
//
// Reads scripts/photos.manifest.json and, for every row, takes the ORIGINAL
// from --src (default ~/Desktop/osppy-fotos, outside the repo — the 26 files
// weigh 91 MB and none of them belongs in git) and writes:
//
//   public/photos/<slug>.webp      long edge 1600, quality 78
//   lib/photos.generated.ts        slug -> { src, width, height, blurDataURL, altEs, altEn }
//
// One size per photo on purpose: next/image derives the rest, and AVIF on
// Vercel. 1600 was sized as twice the widest box a photo was rendered in
// (the areas frame is ~600 CSS px), so a 2400 master would be bytes nobody
// downloads and megabytes everybody clones. Since v5 T3 one photo (`hero`)
// is rendered full-bleed, where 1600 is NOT twice the box: that original is
// 1376x768 and `withoutEnlargement` keeps it there, so it sits BELOW this
// ceiling, not above it. Raising LONG_EDGE cannot help it; only a wider
// original can (plan v5 O-8, contingent on how it looks on a phone).
//
// The blur placeholder is a 16 px WebP inlined as a data URI — the same
// trick next/image's static import does, done by hand because these images
// are addressed by slug at runtime, not imported.
//
// NO CREDITS FILE. The Unsplash and Pexels licenses both ASK for attribution
// and neither REQUIRES it; the operator ruled on 2026-09-03 that the site
// carries none (HQA-D78). Author and photo id stay in the manifest's `file`,
// which is where traceability belongs.
//
//   node scripts/optimize-photos.mjs [--src <dir>] [--only <slug,slug>]
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";
import sharp from "sharp";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? fallback : process.argv[i + 1];
};
const SRC = resolve(arg("src", join(homedir(), "Desktop", "osppy-fotos")));
const ONLY = arg("only", null)?.split(",");
const OUT = join(root, "public", "photos");
const LONG_EDGE = 1600;
const QUALITY = 78;

const manifest = JSON.parse(readFileSync(join(here, "photos.manifest.json"), "utf8"));
const rows = manifest.photos.filter((r) => !ONLY || ONLY.includes(r.slug));

if (!existsSync(SRC)) {
  console.error(
    `no encuentro los originales en\n  ${SRC}\n` +
      "pásame la carpeta con --src. Los originales viven FUERA del repo a propósito.",
  );
  process.exit(1);
}

mkdirSync(OUT, { recursive: true });

const generated = [];
let total = 0;

for (const row of rows) {
  const from = join(SRC, row.file);
  if (!existsSync(from)) {
    console.error(`✗ ${row.slug}: falta el original ${row.file}`);
    process.exit(1);
  }

  const pipeline = sharp(from).rotate().resize({
    width: LONG_EDGE,
    height: LONG_EDGE,
    fit: "inside",
    withoutEnlargement: true,
  });
  const { data, info } = await pipeline
    .webp({ quality: QUALITY })
    .toBuffer({ resolveWithObject: true });
  writeFileSync(join(OUT, `${row.slug}.webp`), data);

  const blur = await sharp(from)
    .rotate()
    .resize({ width: 16 })
    .webp({ quality: 40 })
    .toBuffer();

  generated.push({
    slug: row.slug,
    src: `/photos/${row.slug}.webp`,
    width: info.width,
    height: info.height,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    altEs: row.altEs,
    altEn: row.altEn,
  });

  total += data.length;
  console.log(
    `✓ ${row.slug.padEnd(20)} ${info.width}x${info.height}  ${(data.length / 1024).toFixed(0)} kB`,
  );
}

const ts = `// GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
// Source rows: scripts/photos.manifest.json. Originals live outside the repo.
export type SitePhoto = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
  altEs: string;
  altEn: string;
};

export const PHOTOS = {
${generated
  .map(
    (p) => `  "${p.slug}": {
    src: "${p.src}",
    width: ${p.width},
    height: ${p.height},
    blurDataURL:
      "${p.blurDataURL}",
    altEs: ${JSON.stringify(p.altEs)},
    altEn: ${JSON.stringify(p.altEn)},
  },`,
  )
  .join("\n")}
} as const satisfies Record<string, SitePhoto>;

export type PhotoSlug = keyof typeof PHOTOS;
`;

writeFileSync(join(root, "lib", "photos.generated.ts"), ts);
console.log(
  `\n${generated.length} fotos · ${(total / 1024 / 1024).toFixed(1)} MB en public/photos · lib/photos.generated.ts reescrito`,
);
